export const ICON_PRESETS: Record<string, string> = {
  cart: "🛒",
  bag: "🛍️",
  store: "🏪",
  cook: "🍳",
  clean: "🧹",
  medicine: "💊",
  box: "📦",
  gift: "🎁",
  note: "📝",
  check: "✅",
  home: "🏠",
  dog: "🐶",
  baby: "👶",
  work: "💼",
  flower: "🌸",
  cake: "🎂",
};
